[theme]
primaryColor = "#58A6FF"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#1C1F26"
textColor = "#FAFAFA"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
